### ISSUE TITLE
First days in suggested schedule is always Sundays even though it was defined differently in the sign-up sheet

### ISSUE THREAD

**Issue by marinaluchner** [botcs/wolfson-scheduler#3] opened 2024-01-27 14:49 UTC
Hi,

Hope you are well.

When I define the first sessions of the week as Mon 29th in the Availability sheet, the suggested schedule will pencil in Jan 29th sessions as Sunday.

I don't expect this to be fixed just wanted to give some user feedback.

Best,

LBC captain

**Comment by botcs** [comment] 2024-01-28 07:15
If you could share a copy of the sheet with me (with names potentially obfuscated) I could take a look into it, to reproduce the same error.

(Reached out in email)

Thanks!

**Comment by botcs** [comment] 2024-02-03 04:15
Hi @marinaluchner,

Bug fixed in f64a815.

reason: in the outing keys we only store the dates and only during printing we re-evaluate the day's name (e.g. Monday).

Since the dates always encode the Month and the Day, we need to query the current year when re-evaluating the day.

The bug fix came with some stability improvements as well, by updating `gspread=5.10.0 -> 6.0.0`.

Thanks for spotting the bug

**Closed as completed by botcs** 2024-02-03 04:15 UTC
